#!/usr/bin/env bash

### Setting constants
MAIN_BRANCH='master'
STAGE_BRANCH='stage'
FEATURE_PREFIX='feature/'

### Functions
is_git_available() {
  git --version 2>&1 >/dev/null
  return [[ $? -eq 0 ]]
}

is_git_repository() {
  git rev-parse 2>&1 >/dev/null
  return [[ $? -eq 0 ]]
}

is_branch_existent() {
  git rev-parse --verify --quiet $1 2>&1 >/dev/null
  return [[ $? -eq 0 ]]
}

get_current_branch() {
  local current_branch=$(git rev-parse --abbrev-ref HEAD)
  echo "$current_branch"
}


### Validating GIT
if [[ ! $(is_git_available) ]]; then
  echo 'Please install GIT before running this command.'
  exit 11 
fi

if [[ ! $(is_git_repository) ]]; then
  echo 'This folder is not monitored by a GIT repository.'
  exit 12
fi

if [[ ! $(is_branch_existent $MAIN_BRANCH) ]]; then
  echo 'Do your first commit to master before proceeding with Another-Git-Flow.'
  exit 13
fi


### Commands
case $1 in

  init)
    if [[ -z $2 ]]; then
      echo 'Please provide which feature should be initiated.'
      exit 14
    fi
    local feature_branch="$FEATURE_PREFIX$2"

    if [[ $(is_branch_existent $feature_branch) ]]; then
      echo "Feature already exists."
      exit 15
    fi
    if [[ $MAIN_BRANCH -ne $(get_current_branch) ]]; then
      git checkout master
    fi
    git checkout -b $feature_branch
    echo "Feature $feature_branch initiated."
    exit 0
    ;;

  delete)
    if [[ -z $2 ]]; then
      local branch=$(get_current_branch)
    else
      local branch="$FEATURE_PREFIX$2"
    fi
    if [[ $MAIN_BRANCH -eq $2 || $MAIN_BRANCH -eq $branch || ! $(is_branch_existent $branch) ]]; then
      echo "Invalid branch for deletion."
      exit 16
    fi
    printf "%s \n" "Are you sure you want to delete branch $branch? [y/n]"
    if read -q; then
      if [[ $branch -eq $(get_current_branch) ]]; then
        git checkout $MAIN_BRANCH
      fi
      git branch -D $feature_branch
      echo "Feature $feature_branch deleted successfully."
    else
      echo 'Aborted by user.'
    fi
    exit 0
    ;;

  *)
    echo 'Please provide which subcommand you want to execute with git-feature:'
    echo 'init "feature name"'
    echo 'delete "feature name"'
    exit 99
    ;;  
esac